[project]
name = "celine-pipelines"
version = "0.1.0"
description = "CELINE pipelines toolkit"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celine-utils>=1.5.0",
]

[dependency-groups]
dev = [
    "dumpster-cli>=1.4.0",
    "semver>=3.0.4",
]

